
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Accounting.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Customer_TB
{

    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Family { get; set; }

    public string NumberPhone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public int Reference { get; set; }

}

}
