
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Accounting.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class HardService_TB
{

    public int HardServiceId { get; set; }

    public string HardServiceName { get; set; }

    public Nullable<int> HardServiceAmount { get; set; }

    public string HardServiceCaption { get; set; }

}

}
