//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_TB
    {
        public int ItemId { get; set; }
        public int ItemIdView { get; set; }
        public string ItemName { get; set; }
        public int ItemCategory { get; set; }
        public int ItemAmountKharid { get; set; }
        public int ItemAmountrosh { get; set; }
        public int ItemNumber { get; set; }
        public string ItemCaption { get; set; }
    
        public virtual ItemCategoryType ItemCategoryType { get; set; }
    }
}
