//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategoryType
    {
        public int ItemCategoryTypeId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual Item_TB Item_TB { get; set; }
    }
}
