
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Accounting.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class SoftService_TB
{

    public int SoftServiceId { get; set; }

    public string SoftServiceName { get; set; }

    public Nullable<int> SoftServiceAmount { get; set; }

    public string SoftServiceCaption { get; set; }

}

}
