

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Accounting.DataLayer
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AccountingStore_DBEntities : DbContext
{
    public AccountingStore_DBEntities()
        : base("name=AccountingStore_DBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Customer_TB> Customer_TB { get; set; }

    public virtual DbSet<Item_TB> Item_TB { get; set; }

    public virtual DbSet<SoftService_TB> SoftService_TB { get; set; }

    public virtual DbSet<HardService_TB> HardService_TB { get; set; }

}

}

